# Generated by Django 4.2.5 on 2023-10-04 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp_inheritance', '0004_publication_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='publications',
        ),
    ]
